name: Release
on:
  push:
    branches:
    - main

permissions:
  contents: write

jobs:
  update-tag:
    name: Update the major tag to include the ${{ github.event.inputs.TAG_NAME || github.event.release.tag_name }} changes
    runs-on: ubuntu-latest
    environment:
      # Note: this environment is protected
      name: Release
    steps:
      - name: Update the ${{ env.TAG_NAME }} tag
        id: update-major-tag
        uses: actions/publish-action@v0.3.0
        with:
          source-tag: ${{ env.TAG_NAME }}

  build-and-deploy:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Install and build
      run: |
        npm ci
        npm run build
        
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4
      with: 
        folder: portfolio-site/build
